# Generated by Django 4.2 on 2023-05-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nama',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='angkatan',
            field=models.IntegerField(),
        ),
    ]
