# Generated by Django 4.2.1 on 2023-05-26 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment_followerscount_likepost_post_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_sent', models.CharField(max_length=100)),
                ('user_notif', models.CharField(max_length=100)),
                ('user_notif_image', models.ImageField(upload_to='')),
                ('tipe', models.CharField(max_length=100)),
                ('id_tipe', models.CharField(default=None, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
