# Generated by Django 4.2 on 2023-05-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_nama_alter_profile_angkatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='angkatan',
            field=models.IntegerField(null=True),
        ),
    ]
