# Generated by Django 4.2.1 on 2023-05-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sampulimg',
            field=models.ImageField(default='sampul.png', upload_to='sampul_img'),
        ),
    ]
